<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <ProjectReference Include="..\Identity\ComercialWeb.Mobile.Identity.csproj" />
    <ProjectReference Include="..\..\Common\ComercialWeb.Mobile.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ComercialWeb.Mobile.Tests" />
  </ItemGroup>

</Project>
