<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Modules\Identity\ComercialWeb.Mobile.Identity.csproj" />
    <ProjectReference Include="..\Modules\Catalog\ComercialWeb.Mobile.Catalog.csproj" />
    <ProjectReference Include="..\Modules\Customers\ComercialWeb.Mobile.Customers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\db\migrations\*.sql" LinkBase="migrations" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ComercialWeb.Mobile.Tests" />
  </ItemGroup>

</Project>
