<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Customers\ComercialWeb.Mobile.Customers.csproj" />
    <ProjectReference Include="..\Identity\ComercialWeb.Mobile.Identity.csproj" />
    <ProjectReference Include="..\..\Common\ComercialWeb.Mobile.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ComercialWeb.Mobile.Tests" />
  </ItemGroup>

</Project>
